modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Botania License"

[[mods]]
modId = "botania_retro"
version = "${version}"
displayName = "Botania Retro"
authors = "Kazamata Neri"
description = '''
This addon restores legacy items removed from older versions of Botania, allowing players to relive nostalgic mechanics and designs.
'''

logoFile = "assets/botania_retro/icon.png"

[[dependencies.botania_retro]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botania_retro]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.botania_retro]]
modId = "botania"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"