# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Important Notes:
# Every field you add must be added to the expandProps map in buildSrc/src/main/groovy/multiloader-common.gradle.
# Important Notes:
# Every field you add must be added to the expandProps map in buildSrc/src/main/groovy/multiloader-common.gradle.
# Project
version=1.0.1
group=moe.kazamata_neri
java_version=17
mod_id=botania_retro
mod_name=Botania Retro
mod_author=Kazamata Neri
license=Botania License
credits=
description=This addon restores legacy items removed from older versions of Botania, allowing players to relive nostalgic mechanics and designs.

# Common
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,)
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Deps
botania_version=1.20.1-456

# ThirstLikeMods
tan_fab=maven.modrinth:ge1sOdFH:VaFrDMPi
tan_forge=maven.modrinth:ge1sOdFH:kWVOI0iS
hsc_fab=maven.modrinth:oDobngty:pzJh0p9r
hsc_forge=maven.modrinth:oDobngty:lxSJN2lX
yat_fab=maven.modrinth:HOl2fYpO:qARDoSIU
yat_forge=maven.modrinth:HOl2fYpO:1x8PHF99
suv=maven.modrinth:vg4qcCBb:oGlzVpfO
tfc=maven.modrinth:JaCEZUhg:F35Y7gTr
twt=maven.modrinth:iUheEnjm:v0d2UK5F
lso=maven.modrinth:TQr3t8Sb:BsBOQNzX
realistic=maven.modrinth:vOnTcUsE:iKzmiIdk
dhy=maven.modrinth:qWDh3G0p:60cSGCnr
extreme=maven.modrinth:HUOBN2Zf:3RnojQVJ
