# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=1.0.1
group=moe.KazamataNeri
java_version=21
# Common
minecraft_version=1.21.1
mod_name=Botania Retro
mod_author=Kazamata Neri
mod_id=botania_retro
license=Botania License
credits=Vazkii
description=This addon restores legacy items removed from older versions of Botania, allowing players to relive nostalgic mechanics and designs.
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.1
parchment_version=2024.11.17
# Fabric
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.17.2
# NeoForge
neoforge_version=21.1.206
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Botania
botania_version=457

# ThirstLikeMods
tan_neo=maven.modrinth:ge1sOdFH:mboAbksk
tan_fab=maven.modrinth:ge1sOdFH:dLxSK1xF
suv_neo=maven.modrinth:vg4qcCBb:QdUq0GTi
suv_fab=maven.modrinth:vg4qcCBb:nKLqDdCr
hsc_neo=maven.modrinth:oDobngty:ElJcztcv
hsc_fab=maven.modrinth:oDobngty:hScSK8aA
yat_neo=maven.modrinth:HOl2fYpO:xmk0FTsX
yat_fab=maven.modrinth:HOl2fYpO:VL77oq16
twr=maven.modrinth:B9HAFlgU:Y7Tm4V7W
lso=maven.modrinth:TQr3t8Sb:AZzEduN3
realistic=maven.modrinth:vOnTcUsE:ndDH4B73
dhy=maven.modrinth:qWDh3G0p:4TJ5tNbT
extreme=maven.modrinth:HUOBN2Zf:5BSiWA1f
hunger=maven.modrinth:WmvP7PPI:EGvuWwqU

# ThirstLikeLib
unl=curse.maven:unionlib-367806:5612992
